### ISSUE TITLE
_joinParty and joinParty

### ISSUE THREAD

**Issue by DominikKoller** [DominikKoller/pxt-Parties#4]
We can export functions directly from the cpp file, the block annotations work there as well:
https://makecode.com/defining-blocks

So we don't need the _joinParty in cpp to be forwarded by joinParty in typescript. The only thing is: we want that namespace to be Parties and not PartiesInternal.

**Comment by sarthakjainMagd** [comment]
Yh, the reason I did that was for flexibility if someone wanted to change the way the party was joined they could reimplement the cpp _joinParty (e.g. with a different hash function) but I agree the reimplementation would just as well be exposed straight from the cpp file. And yes, I'll move that to the Parties namespace.
