### ISSUE TITLE
HandleUnicast

### ISSUE THREAD

**Issue by DominikKoller** [DominikKoller/pxt-Parties#5]
I think HandleUnicast shouldn't return a Packet. It may take a packet as an input, then it should worry about whether we're the receiver of that packet (possibly worry about whether to rebound it or not), and then call a library function so that the user can react to whatever is coming in.

Somewhat similar to how it's done in the current radio module (but not exactly the same as they want to have all incoming messages user-handled and we want to handle some without the user, like heartbeat messages)

Looking at the current radio module a bit more it seems to me there's still quite some space for improvement on how we handle messages anyway (but let's do any big restructurings later, if at all).

Interesting: in the current radio module, you can only use one of onRadioReceivedNumber and onRadioReceivedString, not both (ie it doesn't 'tell' you whether you received a number or a string, and therefore lets you only use one at a time)

**Comment by sarthakjainMagd** [comment]
Yes I thought about this and concluded that leaving it as a packet for then (yesterday) made development more flexible for today and tomorrow. In the current radio module , the user is forced to handle packets in only one way AND it must supply the way it wants to handle the packets as well (through function "cb" in radio.ts). We'll need to define a more precise higher level API for receiving a targeted string and move from there.

**Comment by DominikKoller** [comment]
Yea the user should be able to register a listener for strings, and a listener for numbers, etc and we should call the right callbacks for any message we get.

We could also have a listener system so the use can have two functions that are both called when we receive a string (observer pattern) but intuitively I'd think that would be an overkill, bloat our code and require more memory on the device.
