### ISSUE TITLE
broadcasting vs unicasting

### ISSUE THREAD

**Issue by sarthakjainMagd** [DominikKoller/pxt-Parties#6]
why do we have a broadcast  type ? Isn't broadcast already implemented and we're just implementing unicast?

**Comment by DominikKoller** [comment]
We still need a broadcast in our protocol. If you're part of a specific party, you want to be able to broadcast to that specific party. Also rebound will be able to broadcast over an extra hop. Also, receiving a broadcast message you'll be able to tell who it's from, in your party member table, which might be helpful for some games.
